#端口号配置
server:
  port: 8085
#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grapro?serverTimezone=Asia/Beijing&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB     #单个文件最大限制
      max-request-size: 10MB  #多个文件最大限制
#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty

#jwt配置
jwt:
  #颁发者
  issuer: nifeng
  #秘钥
  secret: com.graPro
  #30分钟过期
  expiration: 30

#图片上传
web:
  uploadpath: /www/wwwroot/images/  #图片上传的路径
  load-path: file:/www/wwwroot/images/ #图片访问、加载的路径

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'